### ISSUE TITLE
Correspondence points issue 

### ISSUE THREAD

**Issue by epilepneuro** [tractatus/wholebrain#22]
Hi Daniel,

I encountered another issue during registration that I hope you can help me with. I changed the seg$filter$resize to 0.1; however, along with taking around 5 minutes to load (I assume due to the size of the image) the registration on the left (atlas) has all the correspondence points in a tiny area in the middle with no overlay while the target has the correct correspondence points. The following is the output I receive after running:

```
seg$filter$resize <-0.1
quartz()
regi<-registration(folder, coordinate=-1.79, filter=seg$filter)
```

![Capture](https://user-images.githubusercontent.com/56411825/66663589-fe388d00-ec18-11e9-859d-fb0d458582f8.PNG)

Thanks for the help

**Comment by tractatus** [comment]
Your resize parameter is way too large versus your image as you can barely see the orange outline to the left. The resulting transformation is not a permissible transformation hence your wont see any result.

Decrease the resize parameter so that the orange reference atlas outlines are just a little bit smaller than your brain section.

You also probably want to set your Max value to something smaller so you can see what is going on with your brain section since it looks so dark in this rendering.
```
seg$filter$Max <- 20000
```
Depending on the intensity of fluorescence.

**Comment by epilepneuro** [comment]
Thank you very much!
