### ISSUE TITLE
wholebrain.so: undefined symbol: _ZN2cv3MatD1Ev

### ISSUE THREAD

**Issue by lascqy** [tractatus/wholebrain#42]
OS: centOS8
ROpenCVLite and openCV: 4.52
gcc g++: 8.5.0 20210514

all work fine during the installation until the last step, I want get some help to find which part is wrong:

g++ -std=c++11 -shared -L/home/lascqy/workdir/soft/R/lib64/R/lib -L/usr/local/lib64 -o wholebrain.so CThinPlateSpline.o CoherentPointShift.o DoubleSlider.o ThinPlateSpline.o Widget.o affine.o connectedcomponents3D.o display.o filter.o flatfieldcorrection.o gauss_transform.o gauss_transform_make_default.o getContour.o imageconverter.o laplacianpyramidblending.o lwtimagetest.o makeAtlasNissl.o manualsegmentation.o matrix.o multiresolutiondecomposition.o nonrigid.o normalization.o rigid.o transform.o utils.o wavelet2d.o webfiles.o -L/usr/local/lib/ -lfftw3 -llapack -Wl,-rpath=/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib64 -L/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib64 -L/home/lascqy/workdir/soft/R/lib64/R/lib -lR
installing to /home/lascqy/workdir/soft/R/lib64/R/library/00LOCK-wholebrain/00new/wholebrain/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘wholebrain’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/lascqy/workdir/soft/R/lib64/R/library/00LOCK-wholebrain/00new/wholebrain/libs/wholebrain.so':
  /home/lascqy/workdir/soft/R/lib64/R/library/00LOCK-wholebrain/00new/wholebrain/libs/wholebrain.so: undefined symbol: _ZN2cv3MatD1Ev
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by lascqy** [comment]
and the R version 4.1.0 (2021-05-18)

**Comment by tractatus** [comment]
@lascqy from what I can see your compiler compiles both OpenCV and all of wholebrain successfully. The issue then happens when R tries to load the shared library `wholebrain.so`. At this step the shared library references functions related to `cv3MatD1Ev` in OpenCV but then fails to locate those shared libraries anywhere in your environment:
```
 wholebrain.so: undefined symbol: _ZN2cv3MatD1Ev
```
This tells me that most likely one out of two things are happening:
1) You have multiple versions of OpenCV compiled as shared libraries in any of the paths where ` wholebrain.so` will be looking. For where those paths are look at the `Makevars` file:
https://github.com/tractatus/wholebrain/blob/master/src/Makevars
If you have multiple OpenCV versions then R is compiling using ROpenCVLite but then at runtime tries to link with an older version that exist somewhere else in your path and therefore you are getting linking issues at runtime. 

2) ROpenCVLite which is the package installing opencv for you is not linked properly. If this is the case for example check from R console this command:
```r
ROpenCVLite::opencvConfig("libs")
``` 
and what it produces. Most likely your computer doesn't have this path in its environment or in that folder you wont find any of the opencv shared library files (.so files starting with lib in their filename).

**Comment by lascqy** [comment]
thank you very much!!!!!!!
Indeed, because there is not a guide for installation of wholebrain under CentOS.
I try to fix all the bugs and the dependencies during the installation.

1. Yes, the OS come with openCV 3, but the ROpenCVLite requires the version of openCV exactly match itself. So I build the newer openCV 4.5.2.

2. And, indeed, I found some errors of the return form ROpenCVLite::opencvConfig("libs"):
    -Wl,-rpath=/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib -L/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib -lopencv_calib3d -lopencv_core -lopencv_dnn -lopencv_features2d -lopencv_flann -lopencv_gapi -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_video -lopencv_videoio

     Actually, it's  'lib64'  not 'lib' in the path.

3. Two choices: make a soft link to 'lib64' or change the content of Makevars. I chose the second one. But I made a stupid mistake. I forgot to paste the bold italic part in the text following:

     PKG_LIBS = -L/usr/local/lib/ `pkg-config --libs fftw3` -llapack -Wl,-rpath=/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib -L/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib **_-lopencv_calib3d -lopencv_core -lopencv_dnn -lopencv_features2d -lopencv_flann -lopencv_gapi -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_video -lopencv_videoio_**
PKG_CPPFLAGS = `pkg-config --cflags fftw3` -I/home/lascqy/workdir/soft/R/lib64/R/library/opencv/include/opencv4 -I/home/lascqy/workdir/soft/R/lib64/R/library/opencv/include -I/home/lascqy/workdir/soft/R/lib64/R/library/opencv/include/opencv4/opencv2
PKG_CXXFLAGS = `Rscript -e 'Rcpp:::CxxFlags()'` -I../inst/include "-std=c++11"

4. Finally, it works well~~~~

>g++ -std=gnu++14 -shared -L/home/lascqy/workdir/soft/R/lib64/R/lib -L/usr/local/lib64 -o wholebrain.so CThinPlateSpline.o CoherentPointShift.o DoubleSlider.o ThinPlateSpline.o Widget.o affine.o connectedcomponents3D.o display.o filter.o flatfieldcorrection.o gauss_transform.o gauss_transform_make_default.o getContour.o imageconverter.o laplacianpyramidblending.o lwtimagetest.o makeAtlasNissl.o manualsegmentation.o matrix.o multiresolutiondecomposition.o nonrigid.o normalization.o rigid.o transform.o utils.o wavelet2d.o webfiles.o -L/usr/local/lib/ -lfftw3 -llapack -Wl,-rpath=/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib -L/home/lascqy/workdir/soft/R/lib64/R/library/opencv/lib -lopencv_calib3d -lopencv_core -lopencv_dnn -lopencv_features2d -lopencv_flann -lopencv_gapi -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_video -lopencv_videoio -L/home/lascqy/workdir/soft/R/lib64/R/lib -lR
installing to /home/lascqy/workdir/soft/R/lib64/R/library/00LOCK-wholebrain/00new/wholebrain/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (wholebrain)

**Comment by tractatus** [comment]
That is cool to hear that you solved it! Yes it is very annoying when you get this kind of linking errors because in general it usually means a mismatch between opencv versions and that one or multiple ones are on the system path. But from the error itself it is almost impossible to know.

If centOS comes with OpenCV 3 and ROpenCVLite tends to compile the very latest version (which is 4.5) I have to think about best recommendation for centOS. But probably some sort of environment like conda.

Closing this issue now.

**Comment by lascqy** [comment]
yes, centOS8 comes with OpenCV 3.4.6 so far.
it is really annoying that I found the error in STEP2 above by myself, but fell into a simple mistake in STEP3.

thanks for your advices and all works.
