### ISSUE TITLE
The performance of segment process 

### ISSUE THREAD

**Issue by lascqy** [tractatus/wholebrain#44]
recently, I deal with some cell level data with wholebrain.
for some test case, it works fine.

but, for real full data with about 50000 cells......the interactive segment process become very slow.
when change a para on control panel, I have to wait for 10+ min to see the result.

with a lower downsample para, the cells couldn't be recognized one by one, but a big cluster.

so the adjustment of brain outline is also difficult because it affected by the cells.

is there any tips to pass by this problem?

for example, to decide the brain outline with lower sample para, then segment the cells with higher  sample para?
or
it uses only one thread to do this while my workstation have 120 Xeon core and a RTX3090 graphic card

![微信图片_20210910033114](https://user-images.githubusercontent.com/26109283/132750773-6fc3fa9d-777e-44b3-9520-ababa21d98eb.png)

**Comment by tractatus** [comment]
@lascqy there is a parameter in `segment()` named `numthresh` with default value `numthresh=8`. What this parameter does is that it iteratively searches through the intensity range in linear steps of 8 and then segments all objects at each step. That means that segmentation computationally is done 8 times before displaying the results. The benefit with this parameter is when you have a case of several low intensity objects combined with high intensity objects. However, it is seldom needed so for a quick speed increase you can simply set `numthresh` to a lower number.

**Comment by tractatus** [comment]
10 min for display sounds also crazy high to me. Sounds more like an issue with a mismatch between segmentation parameters and the properties of the image. 

So if you could post the typical dimensions of the image in pixels, theoretical pixel resolution, and a list object with your segmentation parameters. You can get the segmentation parameters with `edit(seg$filter)`.

**Comment by lascqy** [comment]
well~
thanks for your great inspiration.
I may find the problem.
actually, my pic is a maskfile which sets every cell as a circle with radius of 3 pixels and the threshold of gray map is set to 1 .
there are about 40k-50k cells in the half brain.
so the pic has a dimension of 16633x15686 pixels and the  ranges of intensely, soma area and eccentricity are not the problem.

but the resolution is set to 72 pixel per inch. this could result in a wrong size of 231x218 inches while the real size is about 1cm.

I will change the resolution and the para "numthresh' to retest it after this weekend and post the feedback as soon as possible.

embarrassingly, I still have 2 questions:
1. could it use multitheads for this process? I have never used multitheads in R but I could change the codes if it's possible.
2. is there any tools, rules or guides to build a custom altas Rdata for wholebrain? for example, I may want to use wholebrain on other animal's brain.
thanks again ~~~~

**Comment by tractatus** [comment]
Right so 16633x15686 pixels sounds like on the larger end but not very far from the dimensions usually used. 40-50k cells should absolutely not be a problem either.

The parameters that most greatly affects computation time is:
1) downsample
2) resize (resize is just a second layer of downsample that ensures that your image is sampled on a similar spacing as the atlas).
3) numthresh

In addition to this WholeBrain automatically calculates the average intensity for each segmented object and that is the most computational intense task during the segmentation. It sounds to me like you have no use for the average intensity, correct? If so what I could do is add a boolean flag that indicates if mean intensity is needed or not. 

Multithreading is mostdef possible since everything you see at this stage is done from C++ so this can 100% be multithreaded. The only concern with multithreading is how and on what level. OpenMP is definitely the most straightforward way to both ad multithreading to the application as well as to OpenCV but for quite some time Apple has been against OpenMP so adding that as a dependency would in addition to the already quite cumbersome OpenCV build also force the user to build OpenMP and those instructions will differ from OS to OS. 
But Im totally open for suggestions.

Regarding the tools and rules to build your own atlas. Feel free to open a separate issue on what organism you want and what resources you currently have that you think would be useful for making such an atlas and we can discuss that in that specific issue thread.

**Comment by lascqy** [comment]
I'm so sorry I forgot to reply this issue.
yes, set the numthresh to zero with resize= 0.0128 with increase the speed significantly.
close it now
