### ISSUE TITLE
wholebrainsoftware.org

### ISSUE THREAD

**Issue by domjacri** [tractatus/wholebrain#52]
Seems to be an issue with the domain name. Is there a new location for installation instructions/etc?

**Comment by tractatus** [comment]
Hi @domjacri 

Unfortunately, the site is temporarily down due to a miscommunication between the service providers where I'm moving the site. Turns out IT at big universities are a nightmare.

Hopefully, it will be up tomorrow. And yes it is a DNS issue.

Meanwhile, if it is Windows I recommend this excellent tutorial by @matiasandina :
https://matiasandina.github.io/wholebrain_install/

**Comment by domjacri** [comment]
Thanks for the update. Best of luck with IT!
